stages:
  #  - build
  - deploy

#cache:
#  paths:
#    - node_modules/

#build:
#  stage: build
#  only:
#    - main
#  script:
#    - pwd
#    - git log --oneline
#    - ls -la
#    - sudo npm install --force
#    - sudo npm install
#  tags:
#    - neordinary-coreui-react-js-admin
#  when: manual

dev_deploy:
  stage: deploy
  only:
    - main
  variables:
    CONTENT_TYPE: 'Content-type: application/json'
    DATA: '{ text: "[DEV] ??? 배포 완료]", "attachments": [ { "fallback": "", "color": "good", "fields": [ { "title": "REACT_APP_ENV : dev", "short": true } ], "footer": "???", "mrkdwn_in": [ "text" ] } ] }'
  script:
    - pwd
    - git log --oneline
    - ls -la
    - sudo npm install
    - ls -la
    - sudo npm run build-dev
    - sudo ls -la
    - sudo \cp -r -f ./build-dev /var/www/html/web
    - 'curl -X POST -H "$CONTENT_TYPE" --data "$DATA" https://hooks.slack.com/services/???'
  tags:
    - ???
  when: manual

stage_deploy:
  stage: deploy
  only:
    - main
  variables:
    CONTENT_TYPE: 'Content-type: application/json'
    DATA: '{ text: "[STAGE] ??? 배포 완료]", "attachments": [ { "fallback": "", "color": "good", "fields": [ { "title": "REACT_APP_ENV : stage", "short": true } ], "footer": "???", "mrkdwn_in": [ "text" ] } ] }'
  script:
    - pwd
    - git log --oneline
    - ls -la
    - sudo npm install
    - ls -la
    - sudo npm run build-stage
    - sudo ls -la
    - sudo \cp -r -f ./build-stage /var/www/html/web
    - 'curl -X POST -H "$CONTENT_TYPE" --data "$DATA" https://hooks.slack.com/services/???'
  tags:
    - ???
  when: manual

prod_deploy:
  stage: deploy
  only:
    - main
  variables:
    CONTENT_TYPE: 'Content-type: application/json'
    DATA: '{ text: "[PROD] ??? 배포 완료]", "attachments": [ { "fallback": "", "color": "good", "fields": [ { "title": "REACT_APP_ENV : production", "short": true } ], "footer": "???", "mrkdwn_in": [ "text" ] } ] }'
  script:
    - pwd
    - git log --oneline
    - ls -la
    - sudo npm install
    - ls -la
    - sudo npm run build-prod
    - sudo ls -la
    - sudo \cp -r -f ./build /var/www/html/web
    - 'curl -X POST -H "$CONTENT_TYPE" --data "$DATA" https://hooks.slack.com/services/???'
  tags:
    - ???
  when: manual
