const MeterialLDetailModal = require('../../../components/Modal/partnerCenter/users/MeterialLDetailModal')
exports.testUserTableValues = [
  {
    id: 1,
    userName: '122',
    email: 'Test@naver.com',
    phoneNumber: '111-222-3333',
    firstRegistration: '2022-01-24',
    images: [''],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 2,
    userName: '23312',
    email: 'Test@naver.com',
    phoneNumber: '22222-3333-4444',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-01-25',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 3,
    userName: '341231',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: false,
    createdAt: '2022-01-26',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 4,
    userName: '4515',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-01-27',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 5,
    userName: '51235',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-01-28',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 6,
    userName: '61234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: false,
    createdAt: '2022-01-29',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 7,
    userName: '751234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-02-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 8,
    userName: '81235',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-03-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 9,
    userName: '91234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: false,
    createdAt: '2022-03-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 10,
    userName: '101234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-04-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 11,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-03-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 12,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-02-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 13,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 14,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 15,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 16,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 17,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 18,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 19,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
]

// 딜러 지원 리스트
exports.dealerSupportListData = [
  {
    no: 1,
    category: '대리점',
    announcementTitle: '신입공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 2,
    category: '대리점',
    announcementTitle: '기술직군',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-05',
    employEndDate: '',
    status: true,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 3,
    category: '대리점',
    announcementTitle: 'IT공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 4,
    category: '딜러',
    announcementTitle: '마케터 부분 공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 5,
    category: '대리점',
    announcementTitle: '경력직/채용',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 6,
    category: '딜러',
    announcementTitle: '공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 7,
    category: '대리점',
    announcementTitle: '공채입니다',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 8,
    category: '딜러',
    announcementTitle: '공채에요',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 9,
    category: '딜러',
    announcementTitle: 'ㅇㅁㅈㅇㅁㅈ',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 10,
    category: '딜러',
    announcementTitle: '신ㅁㄷㄴㄻㅎ입공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 11,
    category: '딜러',
    announcementTitle: 'ㅁㅎㅁㄷ',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 12,
    category: '딜러',
    announcementTitle: 'ㅁㄷㅎㅁㄷㄴ',
    userName: 'Bibibig',
    employStartDate: '2022-09-01',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
]

exports.testPopupValues = [
  {
    no: 1,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    no: 2,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    no: 3,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    no: 4,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    no: 5,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    no: 6,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    no: 7,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    no: 8,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
]

// 자료실 리스트
exports.meterialListData = [
  {
    no: 1,
    category: '대리점',
    announcementTitle: '신입공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 2,
    category: '대리점',
    announcementTitle: '기술직군',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-05',
    employEndDate: '',
    status: true,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 3,
    category: '대리점',
    announcementTitle: 'IT공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 4,
    category: '딜러',
    announcementTitle: '마케터 부분 공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 5,
    category: '대리점',
    announcementTitle: '경력직/채용',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 6,
    category: '딜러',
    announcementTitle: '공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 7,
    category: '대리점',
    announcementTitle: '공채입니다',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 8,
    category: '딜러',
    announcementTitle: '공채에요',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 9,
    category: '딜러',
    announcementTitle: 'ㅇㅁㅈㅇㅁㅈ',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 10,
    category: '딜러',
    announcementTitle: '신ㅁㄷㄴㄻㅎ입공채',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 11,
    category: '딜러',
    announcementTitle: 'ㅁㅎㅁㄷ',
    userName: 'Bibibig',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    no: 12,
    category: '딜러',
    announcementTitle: 'ㅁㄷㅎㅁㄷㄴ',
    userName: 'Bibibig',
    employStartDate: '2022-09-01',
    email: 'tests.google.com',
    phoneNumber: '010-1111-2222',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'a',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
]
