exports.categorys = {
  servicePlanning: {key: 'servicePlanning', value: '서비스 기획'},
  serviceDevelop: {key: 'serviceDevelop', value: '서비스 개발'},
  design: {key: 'design', value: '디자인'},
  a: '사업 개발',
  b: 'B2B 개발',
  c: 'B2B 운영 ',
  d: '법인 영업',
  e: '채널 영업',
  f: '디바이스 영업',
  g: '디바이스 개발',
  h: 'OEM 관리',
  i: 'A/S 센터',
  j: '경영 관리',
  k: '정산',
  l: '운영 기획',
  m: '고객 지원',
  n: '통합 CS ',
  i: '현장 지원-기술 지원',
  p: '현장 지원 - 물류',
  q: '운영 혁신 TF',
}
