exports.testOptions = [
  {
    value: 'test',
    label: '테스트',
  },
  {
    value: 'test1',
    label: '테스트1',
  },
  {
    value: 'test2',
    label: '테스트2',
  },
]

exports.testTableValues = [
  {
    id: 1,
    smallColumn: '1',
    normalColumn: '1',
    largeColumn: '1',
  },
  {
    id: 2,
    smallColumn: '2',
    normalColumn: '2',
    largeColumn: '2',
  },
  {
    id: 3,
    smallColumn: '3',
    normalColumn: '3',
    largeColumn: '3',
  },
]

exports.testTableColumns = [
  {key: 'id', label: 'ID', _props: {className: 'small'}},
  {key: 'smallColumn', label: '스몰 사이즈', _props: {className: 'small'}},
  {key: 'normalColumn', label: '노말 사이즈'},
  {key: 'largeColumn', label: '라지 사이즈', _props: {className: 'large'}},
]

exports.testUserTableValues = [
  {
    id: 1,
    userName: '122',
    email: 'Test@naver.com',
    phoneNumber: '111-222-3333',
    firstRegistration: '2022-01-24',
    images: [''],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 2,
    userName: '23312',
    email: 'Test@naver.com',
    phoneNumber: '22222-3333-4444',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-01-25',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 3,
    userName: '341231',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: false,
    createdAt: '2022-01-26',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 4,
    userName: '4515',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-01-27',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 5,
    userName: '51235',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-01-28',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 6,
    userName: '61234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: false,
    createdAt: '2022-01-29',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 7,
    userName: '751234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-02-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 8,
    userName: '81235',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-03-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 9,
    userName: '91234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: false,
    createdAt: '2022-03-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 10,
    userName: '101234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [],
    status: true,
    createdAt: '2022-04-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 11,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-03-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 12,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-02-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 13,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 14,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 15,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 16,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 17,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 18,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
  {
    id: 19,
    userName: '1151234',
    email: 'Test@naver.com',
    phoneNumber: '3123-41231-12412312',
    firstRegistration: '2022-01-24',
    images: [
      'https://img1.daumcdn.net/thumb/C176x176/?fname=https://k.kakaocdn.net/dn/s5xc6/btrDZImdqkO/MUDaKD6v0M4rxHglbFJ8o1/img.png',
    ],
    status: false,
    createdAt: '2022-01-24',
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
  },
]

exports.testEmployments = [
  {
    No: 1,
    category: 'new',
    employName: '신입공채',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'SERVICE_PLANNING',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 2,
    category: 'new',
    employName: '기술직군',
    employStartDate: '2022-09-05',
    employEndDate: '',
    status: true,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'SERVICE_DEVELOPMENT',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 3,
    category: 'new',
    employName: 'IT공채',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'OEM_MANAGEMENT',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 4,
    category: 'new',
    employName: '마케터 부분 공채',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'OEM_MANAGEMENT',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 5,
    category: 'new',
    employName: '경력직/채용',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'CUSTOMER_SUPPORT',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 6,
    category: 'new',
    employName: '공채',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'OPERATIONAL_INNOVATION_TF',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 7,
    category: 'new',
    employName: '공채입니다',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'ONSITE_SUPPORT_TECHNICAL_SUPPORT',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 8,
    category: 'new',
    employName: '공채에요',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'B2B_OPERATION',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 9,
    category: 'new',
    employName: 'ㅇㅁㅈㅇㅁㅈ',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'CHANNEL_SALES',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 10,
    category: 'new',
    employName: '신ㅁㄷㄴㄻㅎ입공채',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'SETTLEMENT',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 11,
    category: 'new',
    employName: 'ㅁㅎㅁㄷ',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'B2B_DEVELOPMENT',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
  {
    No: 12,
    category: 'new',
    employName: 'ㅁㄷㅎㅁㄷㄴ',
    employStartDate: '2022-09-01',
    employEndDate: '2022-09-31',
    status: false,
    businessName: '',
    businessNumber: '',
    businessRegistration: '',
    businessAddress: '',
    employbannerImg: 'www.naver.com',
    employmentType: 'SERVICE_PLANNING',
    workArea: '기획부',
    education: 'c',
    career: 'b',
    des: '안녕하세요',
    qualifications: '반갑습니다.',
    preferentiaTreatment: 'dkdkdkdkdk',
    reason: '이유',
    departmentStatus: 'dkvkcxm',
    etc: '',
  },
]

exports.testPopupValues = [
  {
    No: 1,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    No: 2,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    No: 3,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    No: 4,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    No: 5,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    No: 6,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    No: 7,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
  {
    No: 8,
    popUpName: 'new',
    popUpImg: 'ㅁㄷㅎㅁㄷㄴ',
  },
]

exports.testTalentValues = [
  {
    No: 0,
    name: '테스터1',
    email: 'test01@naver.com',
    pNum: '010-1234-0001',
    position: 'a',
  },
  {
    No: 1,
    name: '테스터2',
    email: 'test02@naver.com',
    pNum: '010-1234-0002',
    position: 'b',
  },
  {
    No: 2,
    name: '테스터3',
    email: 'test03@naver.com',
    pNum: '010-1234-0003',
    position: 'c',
  },
  {
    No: 3,
    name: '테스터4',
    email: 'test04@naver.com',
    pNum: '010-1234-0004',
    position: 'd',
  },
  {
    No: 4,
    name: '테스터5',
    email: 'test05@naver.com',
    pNum: '010-1234-0005',
    position: 'e',
  },
  {
    No: 5,
    name: '테스터6',
    email: 'test06@naver.com',
    pNum: '010-1234-0006',
    position: 'b',
  },
  {
    No: 6,
    name: '테스터7',
    email: 'test07@naver.com',
    pNum: '010-1234-0007',
    position: 'f',
  },
  {
    No: 7,
    name: '테스터8',
    email: 'test08@naver.com',
    pNum: '010-1234-0008',
    position: 'g',
  },
  {
    No: 8,
    name: '테스터9',
    email: 'test09@naver.com',
    pNum: '010-1234-0009',
    position: 'h',
  },
  {
    No: 9,
    name: '테스터10',
    email: 'test10@naver.com',
    pNum: '010-1234-0001',
    position: 'i',
  },
  {
    No: 10,
    name: '테스터11',
    email: 'test11@naver.com',
    pNum: '010-1234-0011',
    position: 'j',
  },
  {
    No: 11,
    name: '테스터12',
    email: 'test12@naver.com',
    pNum: '010-1234-0012',
    position: 'k',
  },
]

exports.testQnAValues = [
  {
    No: 0,
    name: '테스터1',
    email: 'test01@naver.com',
    pNum: '010-1234-0001',
    inquiryType: 'a',
  },
  {
    No: 1,
    name: '테스터2',
    email: 'test02@naver.com',
    pNum: '010-1234-0002',
    inquiryType: 'b',
  },
  {
    No: 2,
    name: '테스터3',
    email: 'test03@naver.com',
    pNum: '010-1234-0003',
    inquiryType: 'c',
  },
  {
    No: 3,
    name: '테스터4',
    email: 'test04@naver.com',
    pNum: '010-1234-0004',
    inquiryType: 'd',
  },
  {
    No: 4,
    name: '테스터5',
    email: 'test05@naver.com',
    pNum: '010-1234-0005',
    inquiryType: 'e',
  },
  {
    No: 5,
    name: '테스터6',
    email: 'test06@naver.com',
    pNum: '010-1234-0006',
    inquiryType: 'b',
  },
  {
    No: 6,
    name: '테스터7',
    email: 'test07@naver.com',
    pNum: '010-1234-0007',
    inquiryType: 'a',
  },
  {
    No: 7,
    name: '테스터8',
    email: 'test08@naver.com',
    pNum: '010-1234-0008',
    inquiryType: 'b',
  },
  {
    No: 8,
    name: '테스터9',
    email: 'test09@naver.com',
    pNum: '010-1234-0009',
    inquiryType: 'b',
  },
  {
    No: 9,
    name: '테스터10',
    email: 'test10@naver.com',
    pNum: '010-1234-0001',
    inquiryType: 'c',
  },
  {
    No: 10,
    name: '테스터11',
    email: 'test11@naver.com',
    pNum: '010-1234-0011',
    inquiryType: 'c',
  },
  {
    No: 11,
    name: '테스터12',
    email: 'test12@naver.com',
    pNum: '010-1234-0012',
    inquiryType: 'd',
  },
]
